"use-client";

import "./globals.css";
import RootRecoil from "../atoms/recoilWrapper";
import "cesium/Build/Cesium/Widgets/widgets.css";
import SessionProvider from "@/components/SessionProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RootRecoil>
          <SessionProvider>{children}</SessionProvider>
          <ToastContainer />
        </RootRecoil>
      </body>
    </html>
  );
}
